#!/bin/bash

CHROMEDRIVER_PATH="/usr/local/bin/chromedriver"
echo "latest chrome version: $CHROME_DRIVER_VERSION"

# get the latest version, will be stored as a string in a file LATEST_RELEASE
wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE
CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE)

echo 'downloading'
wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_mac64.zip -P ~/

ZIP_FILENAME="chromedriver_mac64.zip"

echo 'unzipping'
unzip -o ~/$ZIP_FILENAME -d ~/
rm ~/$ZIP_FILENAME
mv -f ~/chromedriver $CHROMEDRIVER_PATH

chmod 0755 $CHROMEDRIVER_PATH

echo "finished! chromedriver version $(chromedriver --version) installed"
echo "cleaning up LATEST_RELEASE file"
rm -v LATEST_RELEASE
echo "done"
