#!/bin/bash

CHROMEDRIVER_PATH="/usr/local/bin/chromedriver"
echo "latest chrome version: $CHROME_DRIVER_VERSION"


URL="https://googlechromelabs.github.io/chrome-for-testing/#stable"
HTML=$(curl -s "$URL")
# scrape the latest version string from the HTML
CHROMEDRIVER_VERSION=$(echo "$HTML" | grep -A1 'tr class=status-ok' | grep -o '<code>[^<]*</code>' | sed -n 's/<code>\(.*\)<\/code>/\1/p' | head -1)

echo 'downloading'
wget -N 	https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/mac-x64/chromedriver-mac-x64.zip -P ~/

ZIP_FILENAME="chromedriver-mac-x64.zip"

echo 'unzipping'
unzip -o ~/$ZIP_FILENAME -d ~/
rm ~/$ZIP_FILENAME
mv -f ~/chromedriver-mac-x64/chromedriver $CHROMEDRIVER_PATH

chmod 0755 $CHROMEDRIVER_PATH

echo "finished! chromedriver version $(chromedriver --version) installed"
echo "cleaning up ~/chromedriver-mac-x64"
rm -rfv ~/chromedriver-mac-x64
echo "done"
