#!/bin/bash

# assumes latest chrome version is installed
# scrape latest chromedriver stable release version from https://googlechromelabs.github.io/chrome-for-testing/#stable
# then install that version

CHROMEDRIVER_LOCAL_PATH="/usr/local/bin/chromedriver"

URL="https://googlechromelabs.github.io/chrome-for-testing/#stable"
HTML=$(curl -s "$URL")
# scrape the latest version string from the HTML
CHROMEDRIVER_VERSION=$(echo "$HTML" | grep -A1 'tr class=status-ok' | grep -o '<code>[^<]*</code>' | sed -n 's/<code>\(.*\)<\/code>/\1/p' | head -1)

echo "Extracted version: $CHROMEDRIVER_VERSION"

wget -N https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/mac-x64/chromedriver-mac-x64.zip -P ~/

ZIP_FILENAME="chromedriver-mac-x64.zip"

unzip -o ~/$ZIP_FILENAME -d ~/
rm ~/$ZIP_FILENAME
mv -f ~/chromedriver-mac-x64/chromedriver $CHROMEDRIVER_LOCAL_PATH
mv -f ~/chromedriver-mac-x64/LICENSE.chromedriver ~/

chmod 0755 $CHROMEDRIVER_LOCAL_PATH

echo "finished! chromedriver version $(chromedriver --version) installed"
