#!/bin/bash

# get the version that matches the installed google chrone version
CHROMEDRIVER_PATH="/usr/local/bin/chromedriver"
echo "latest chrome version: $CHROME_DRIVER_VERSION"

CHROME_VERSION=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | awk '{ print $3 }')

wget -N https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/mac-x64/chromedriver-mac-x64.zip -P ~/

ZIP_FILENAME="chromedriver-mac-x64.zip"

unzip -o ~/$ZIP_FILENAME -d ~/
rm ~/$ZIP_FILENAME
mv -f ~/chromedriver-mac-x64/chromedriver $CHROMEDRIVER_PATH
mv -f ~/chromedriver-mac-x64/LICENSE.chromedriver ~/

chmod 0755 $CHROMEDRIVER_PATH

echo "finished! chromedriver version $(chromedriver --version) installed"
